language: node_js
node_js:
  - "v8.10.0"
services:
  - postgresql
env:
  - DATABASE_URL ='postgresql://postgres@localhost:5432/greetnames'
before_script:
  - psql -c 'CREATE DATABASE greetnames;' -U postgres
  - psql -U postgres -d greetnames -a -f base.sql