language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetnames

node_js:
  - "v8.10.0"

before_script:
  - psql -c 'CREATE DATABASE greetnames;' -U postgres
  - psql -U postgres -d greetnames -a -f base.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
