language: node_js
node_js:
  - "v8.10.0"
services:
  -postgresql
env:
  -DATABASE_URL ='postgresql://postgresql@localhost/greetnames'
before_script:
- psql -c 'CREATE DATABASE greetnames;' -u postgres
- psql -u postgres -d greetnames -a -f table.sql